#!/bin/bash

if [ ! -d "$1" -o ! -r "$1" -o $# -ne 2 ] || (echo $2|grep -iq "[^0-9]");
	then
		echo "Uso : ejercicio1 dir valor numerico"
	else
		echo "find $1 -size -$2c">archivosSizN.txt
		find $1 -size -$2c>>archivosSizN.txt
fi
