#!/bin/bash

#crea los archivos loop0 y loop1

mknod /dev/loop0 b 7 0
mknod /dev/loop1 b 7 1

#crea un archivo de 20MB y otro de 30MB en tu sistema de archivos

dd if=/dev/zero of=/root/archivo_SA20 bs=2k count=10000
dd if=/dev/zero of=/root/archivo_SA30 bs=3k count=10000

#ahora vamos asocionar un archivo loop a uno de los archivos creados 

losetup /dev/loop0 /root/archivo_SA20
losetup /dev/loop1 /root/archivo_SA30

#se puede comprobar la configuracion de tus discos con fdisk -l /dev/loop0 /dev/loop1
#aqui iria la parte de hacer fdisk nombre, n, p, 1, w

#creacion de sistema de archivos asociado a cada particion con una etiqueta de volumen -L

mke2fs -t ext3 /dev/loop0 -L LABEL_ext3
mke2fs -t ext4 /dev/loop1 -L LABEL_ext4

#montar los sistemas de archivos ya creados

mkdir /mnt/SA_ext3
mkdir /mnt/LABEL_ext4

mount -t ext3 /dev/loop0 -r /mnt/SA_ext3   #el -r es de lectura y el nombre es /dev/loop0
umount /dev/loop0
mount -t ext4 /dev/loop1 -o dirsync /mnt/LABEL_ext4      #sincronizada sus operaciones de E/S
umount /dev/loop1


#lo realizado arriba en una linea en el archivo /etc/fstab abierto con vi en el arranque del sistema seria

/dev/loop0 /mnt/SA_ext3 ext3 auto,ro 0 0

/dev/loop1 /mnt/LABEL_ext4 ext4 auto,dirsync 0 0


#----------------------------------------------------------
#fdisk -l /dev/loop0 /dev/loop1

#fdisk /dev/loop0 		Te da un menú de opciones con m(como el man vaya)

#fdisk >> n >> e \ p		e extended \ p primary(1-4), como solo queremos una entrada 				hacemos primary para usar todo ese espacio como un "pen-drive" virtual

#fdisk >> n >> p >> 1	
#si usamos fdisk >> p nos sale esto:
#      Device Boot      Start         End      Blocks   Id  System
#/dev/loop0p1            2048       39999       18976   83  Linux

#Esto solo está en RAM, para escribirla en disco debemos usar "w"

#inodos -> estructuras de metadatos que soporta el archivo(?)
#	con ls -li podemos verlos, sería el 14239	
#-rw-r--r-- 1 root root 20480000 Oct  1 06:33 archivo_SA20		<-- ls -l
#14239 -rw-r--r-- 1 root root 20480000 Oct  1 06:33 archivo_SA20		<-- ls -li	

#man mke2fs
#mke2fs -t ext3 /dev/loop0 -L LABEL_ext3		Con -L LABEL_ext3 le ponemos la LABEL

#tune2fs /dev/loop0	o 	tune2fs -l /dev/loop0		info para tunear/modificar

#Ahora montamos la unidad virtual
#ls -la /mnt/				Para ver las unidades
#mount -t ext3 /dev/loop0 /mnt		Monta nuestro "disco" creado en /mnt

#Para desmontar usamos umount y el loop /dev/loop0 por ejemplo, así para desmontar el disco que hemos montado pondríamos:
#umount /dev/loop0		Si pusieramos umount /mnt/lost+found no funcionaría
