#! /bin/bash

if [ $1-eq-1 ]
	then
		echo "La primera expresion es cierta : $1"
else
	echo "La primera expresion es falsa:$1"
fi

if [ $2-eq-1 ]
	then
		echo "La segunda expresion es cierta:$2"
else
	echo "La segunda expresion es falsa:$2"
fi

if [ $1-lt-$2 ]
	then
		echo "El primer parametro es mas pequeño que el segundo"
elif [ $1-gt-$2 ]
then
	echo "EL primer parametro es mas grande que el segundo"
else
	echo "Son iguales"
fi

