#!/bin/bash
cat /etc/passwd | cut -d ":" -f 1 | grep $1 &> /dev/null
var="$?"
if [ "$var" == "0" ]; then
echo "El usuario $1 tiene cuenta en el sistema"
else
echo "El usuario $1 NO tiene cuenta en el sistema"
fi
