#!/bin/bash
if [[ $# -ne 3 ]] #Se podria haber usa el corchete simple y en vez de ne !=
	then echo "Error en el numero de argumentos, introduzca 3 argumentos separados por un espacio, siendo el primero un directorio, el segundo un comando y el tercero una palabra"; exit
else
#Ahora contaremos el numero de ficheros NO ejecutables del directorio pasado como primer argumento e imprimiremos un mensaje en pantalla. 
	E=`find $1 -executable | wc -l`		#Asignamos el numero de ficheros ejecutables a una variable "X" para luego mostrarla en el mensaje
	N=`find $1 | wc -l`			#Asignamos el numero de ficheros totales
	X=`expr $N - $E`			#Restamos el numero de archivos ejecutables al numero de ficheros totales para obtener los NO ejecutables
	echo "De un total de $N ficheros, hay $X ficheros no ejecutables"	
#Ahora mostraremos las 10 primeras líneas del archivo "ayuda", que contiene la orden man relativa al segundo argumento.
	man $2 > ~/ayuda 
	head ~/ayuda | cat
#Ahora encontraremos la palabra dada en el tercer argumento en el fichero "ayuda" y almacenaremos la línea en la que se encuentra en un fichero llamado "resultado"
	grep -n $3 ~/ayuda > ~/resultado
fi
	
