#! /bin/bash

if [ $1-eq-$2 ]
	then
		echo "La igualdad es cierta : 1 "
else
	echo "La igualdad es falsa: 0 "
fi

if [ $2-gt-$1 ]
	then
		echo "El segundo mayor que el primero es cierta: 1 "
else
	echo "El segundo mayor que el primero es falso: 0 "
fi

if [ $2-lt-$1 ]
	then
		echo "El primero mayor que el segundo es cierta: 1 "
else
	echo "El primero mayor que el segundo es falso: 0 "
fi

if [ $1-lt-$2 ]
	then
		echo "El primer parametro es mas pequeño que el segundo"
elif [ $1-gt-$2 ]
then
	echo "EL primer parametro es mas grande que el segundo"
else
	echo "Son iguales"
fi
